### ISSUE TITLE
vROps 7.0 compatibility

### ISSUE THREAD

**Issue by cmargaria** [vmware/vrops-export#16]
It seems that the tool is not compatible with vROps 7.0. Have been tested with this release?

**Comment by prydin** [comment]
@cmargaria I just tested this on vR Ops 7.0 and it works fine for me. What error message do you get?

**Comment by cmargaria** [comment]
Hi,

I doublechecked and everything was fine.

Thanks

Cesare Margaria
Senior Technical Account Manager
cmargaria@vmware.com<mailto:cmargaria@vmware.com>
Mobile: +39 3454389883
Via Spadolini 5 – 20141 – Milan – Italy
[cid:image001.png@01D2FF10.226D3E30]
