### ISSUE TITLE
Several metrics in crops-export tool not returning data

### ISSUE THREAD

**Issue by tnardi-123** [vmware/vrops-export#24]
We have been trying to use the export tool to download metrics but aren't getting any data back for the metrics in the file below. We are able to get other metrics back for these instances so know that the issue isn't with the instances and we are able to retrieve these particular metrics using the custom reporting, so we know that the data is available.
 
We have an open ticket with VMWare and they asked us to open an issue on github.
 
YAML FILE:
 
resourceType: VirtualMachine
rollupType: AVG
rollupMinutes: 1440
dateFormat: "yyyy-MM-dd HH:mm:ss"
fields:
 
# DISK fields
- alias: DISK_SPACE_VM_USED_GB
   metric: diskspace|used
- alias: IOPS_AVG
   metric: virtualDisk|commandsAveraged_average
- alias: LATENCY_AVG
   metric: virtualDisk|totalLatency
- alias: THROUGHPUT_KBPS_AVG
   metric:  virtualDisk|usage
- alias: OUTSTANDING_IO_REQUESTS_AVG
   metric: virtualDisk|vDiskOIO
# Network
- alias: TRANSMITTED_PACKETS_DROPPED_AVG
   metric: net|dropppedTx_summation

**Comment by prydin** [comment]
Hi! I'm investigating this right now. Will get back to you shortly.

**Comment by prydin** [comment]
I found the problem. If you want to export the roll-up of all instances, you need the ```:Aggregate of all instances``` instance specifier.

For example:
```
- alias: iops
  metric: virtualDisk:Aggregate of all instances|commandsAveraged_average
```

Here's a file that works in my lab:
https://gist.github.com/prydin/7532402a93c9140cd5c95b9ac5c7e48b

**Comment by tnardi-123** [comment]
Yay! This worked for all the metrics except for the one pulling back the network data.

When you ran it in your lab, did you get network data back?

Tonya R. Nardi
Converged Infrastructure Capacity Management
PNC Financial Services

412-915-4434 (c)
tonya.nardi@pnc.com<mailto:tonya.nardi@pnc.com>

**Comment by prydin** [comment]
Looks like you misspelled ```droppedTx_summarion``` (three p:s)...

**Comment by tnardi-123** [comment]
OOOPS! Thank you so much. We’re up and running now.

Really appreciate your help.

Tonya R. Nardi
Converged Infrastructure Capacity Management
PNC Financial Services

412-915-4434 (c)
tonya.nardi@pnc.com<mailto:tonya.nardi@pnc.com>

**Comment by prydin** [comment]
Good to hear it worked out! Closing this now.

**Comment by tnardi-123** [comment]
May I ask one more question?

We’re trying to collect data for ‘yesterday’; that is, the period between midnight and 11:59 of the day prior. The way that the YAML we provided pulls data is for the 24 hour period immediately prior to the file being run which means that if we want to pull MAX and AVG metrics(for example) we are getting different periods since the files aren’t run at precisely the same time.

Is there a way to specify an absolute time range as opposed to a relative time range using the vrops-export tool without having to physically update the file on a daily basis?

Thanks!

Tonya




The contents of this email are the property of PNC. If it was not addressed to you, you have no legal right to read it. If you think you received it in error, please notify the sender. Do not forward or copy without permission of the sender. This message may be considered a commercial electronic message under Canadian law or this message may contain an advertisement of a product or service and thus may constitute a commercial electronic mail message under US law. You may unsubscribe at any time from receiving commercial electronic messages from PNC at http://pages.e.pnc.com/globalunsub/
PNC, 249 Fifth Avenue, Pittsburgh, PA 15222; pnc.com
