### ISSUE TITLE
Problem pulling PROPERTY data for VMs 

### ISSUE THREAD

**Issue by wssunder** [vmware/vrops-export#37]
We're having a problem pulling property data for VMs from vROPS using the vrops-export tool.  It has operated quite nicely in the past, and a number of folks in our reporting areas are using it for their customized reports.
 
However, now with 8.1.1 and 8.3.0, we're unable to pull any property data; with metrics, no issues.  This is happening with our production vROPS clusters, as well as our test clusters.  The tools reports back null fields, and we know the data is being collected at vROPS from vCenter.  Here are two example fields we're trying to retrieve, with no success:
 
  # Guest OS
  - alias: guestOS
    prop: config|Name
  - alias: name
    prop: summary|guest|hostname

**Comment by prydin** [comment]
The properties in the file supplied were misspelled.
