### ISSUE TITLE
Grafana export

### ISSUE THREAD

**Issue by AlainGeenrits** [vmware/vrops-export#58]
### Is your feature request related to a problem? Please describe.

I would like to see the possibility to export to Grafana.

### Describe the solution you'd like

Additional export format like json, Wavefront. 

### Describe alternatives you've considered

Maybe json or sql will work too, probably need to test that.

**Comment by prydin** [comment]
Have you tried the "json" output format? There's a json.yaml file in the samples directory.

It would be helpful if you could give some details on what you're trying to do. Is there a specific json format you're looking for?

**Comment by prydin** [comment]
We just released a plugin for Grafana that reads directly from vR Ops. Check it out here: https://github.com/prydin/aria-operations-plug-in-for-grafana

Closing this issue since this is addressed elsewhere.
